### ISSUE TITLE
support jmeter plugins in this cookbook

### ISSUE THREAD

**Issue by yasuhiroki** [johnbellone/jmeter-cookbook#7]
If this cookbook can install jmeter plugins (http://jmeter-plugins.org/), it makes me happy.

**Comment by sworisbreathing** [comment]
I've been looking into this today for a wrapper cookbook I'm building. The main issue I'm running into is getting `ark` to unpack the zips into `/usr/local/jmeter/` instead of `/usr/local/jmeter/JMeterPlugins-Standard`, `/usr/local/jmeter/JMeterPlugins-Extras`, `/usr/local/jmeter/JMeterPlugins-ExtrasLibs`, etc. because ark internally [adds the resource name to the directory path](https://github.com/burtlo/ark/blob/v0.9.0/libraries/default.rb#L185).

It seems a bit hackish, but I've been able to get it working like so:

``` ruby
include_recipe 'ark::default' # install ark package dependencies

plugins = [
  {
    name: 'JMeterPlugins-Standard',
    version: '1.3.1',
    url: 'http://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.3.1.zip'
  },
  {
    name: 'JMeterPlugins-Extras',
    version: '1.3.1',
    url: 'http://jmeter-plugins.org/downloads/file/JMeterPlugins-Extras-1.3.1.zip'
  },
  {
    name: 'JMeterPlugins-ExtrasLibs',
    version: '1.3.1',
    url: 'http://jmeter-plugins.org/downloads/file/JMeterPlugins-ExtrasLibs-1.3.1.zip'
  }
]

jmeter_home = File.join(node['ark']['prefix_home'], 'jmeter')

plugins.each do |plugin|
  ark plugin[:name] do
    url plugin[:url]
    version plugin[:version]
    path jmeter_home
    strip_components 0
    name '' # This is a bit hackish...
    action :put
  end
end
```

**Comment by yasuhiroki** [comment]
@sworisbreathing 
Thank you for your response!
I had been to implement using `remote_file` and `execute` resource for resolving my issue. 
But, I guess your code is better than my implementation. I will refer it!

**Comment by yasuhiroki** [comment]
I had been resolved this issue. Thank you.
